#!/usr/bin/env python3
# DESCRIPTION: Verilator: Verilog Test driver/expect definition
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of either the GNU Lesser General Public License Version 3
# or the Perl Artistic License Version 2.0.
# SPDX-FileCopyrightText: 2026 Wilson Snyder
# SPDX-License-Identifier: LGPL-3.0-only OR Artistic-2.0

import vltest_bootstrap

# Large generated hierarchy; not useful for threaded test matrix.
test.scenarios('vlt')
test.top_filename = os.path.join(test.obj_dir, 't_opt_inline_depth.v')

if test.have_dev_gcov:
    test.skip("Too slow with code coverage")

test.timeout(40 if not test.have_dev_asan else 80)

def gen(filename, depth):
    with open(filename, 'w', encoding='utf8') as fh:
        fh.write('// Generated by t_opt_inline_depth.py\n')
        fh.write('module leaf(input logic i, output logic o);\n')
        fh.write('  assign o = i;\n')
        fh.write('endmodule\n\n')
        for idx in range(depth):
            fh.write(f'module m{idx}(input logic i, output logic o);\n')
            if idx == 0:
                fh.write('  leaf u_leaf(.i(i), .o(o));\n')
            else:
                fh.write('  logic t;\n')
                fh.write(f'  m{idx - 1} u_prev(.i(i), .o(t));\n')
                fh.write('  assign o = t;\n')
            fh.write('endmodule\n\n')
        fh.write('module t;\n')
        fh.write('  logic a;\n')
        fh.write('  logic b;\n')
        fh.write(f'  m{depth - 1} u_top(.i(a), .o(b));\n')
        fh.write('endmodule\n')

# Keep deep enough to stress inline-depth recursion on auto-inline paths.
gen(test.top_filename, 7000)

test.lint()

test.passes()
